packages:
  - .

catalog:
  '@types/react': ^19.3.0

overrides:
  '@types/react': 'catalog:'
  idb-keyval: 'npm:taro-idb-keyval'

autoInstallPeers: false
minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
